services:
  main-backend:
    build:
      context: ../
      dockerfile: ./main-backend/Dockerfile
    env_file:
      - ./env/staging.env
    environment:
      PYTHONUNBUFFERED: "1"
      FASTAPI_ENV: staging
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  community-backend:
    build:
      context: ../
      dockerfile: ./community-backend/Dockerfile
    env_file:
      - ./env/staging.env
    environment:
      PYTHONUNBUFFERED: "1"
      FASTAPI_ENV: staging
      HOST: 0.0.0.0
      PORT: 5001
    ports:
      - "127.0.0.1:15001:5001"
    restart: unless-stopped

  activity-backend:
    build:
      context: ../
      dockerfile: ./activity-backend/Dockerfile
    env_file:
      - ./env/staging.env
    environment:
      PYTHONUNBUFFERED: "1"
      FASTAPI_ENV: staging
      HOST: 0.0.0.0
      PORT: 5100
    ports:
      - "127.0.0.1:15100:5100"
    restart: unless-stopped